apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: NodePort
  selector:
    app: app-server
  ports:
    - protocol: TCP
      port: 6000      
      targetPort: 8000
      nodePort: 32000