apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-server
  template:
    metadata:
      labels:
        app: app-server
    spec:
      containers:
      - name: app
        image: ryanangweihao/rang012_docker_repository:Disinformation_JIECHUNG
        ports:
        - containerPort: 8000
      imagePullSecrets:
      - name: regcred