apiVersion: apps/v1
kind: Deployment
metadata:
  name: disinformation-deployment
  labels:
    app: disinformation-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: disinformation-server
  template:
    metadata:
      labels:
        app: disinformation-server
    spec:
      containers:
      - name: disinformation
        image: tegexplore/pda-2022:disinformation_branch-3db0d57
        ports:
        - containerPort: 8020
      imagePullSecrets:
      - name: dockercred
