apiVersion: apps/v1
kind: Deployment
metadata:
  name: disinformation-deployment
  labels:
    app: disinformation-server
spec:
  replicas: 1   # Always set it to '1' if you are testing it out
  selector:
    matchLabels:
      app: disinformation-server
  template:
    metadata:
      labels:
        app: disinformation-server
    spec:
      containers:
      - name: disinformation
        image: ...
        ports:
        - containerPort: 8020
      imagePullSecrets:
      - name: dockercred
