apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-deployment
  labels:
    app: main-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: main-server
  template:
    metadata:
      labels:
        app: main-server
    spec:
      containers:
      - name: main
        image: tegexplore/pda-2022:main_branch-9f76563
        ports:
        - containerPort: 8010
      imagePullSecrets:
      - name: dockercred
