apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-deployment
  labels:
    app: main-server
spec:
  replicas: 1         # Good practice to set as '1' when stil in TEST/DEV stage
  selector:
    matchLabels:
      app: main-server
  template:
    metadata:
      labels:
        app: main-server
    spec:
      containers:
      - name: main
        image: ...
        ports:
        - containerPort: 8010
      imagePullSecrets:
      - name: dockercred
