apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: nginx-proxy
spec:
  virtualhost:
    fqdn: ryan-asap.com
  routes:
    - conditions:
      - prefix: /
      services:
        - name: asap-service
          port: 80
