apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-statefulset
spec:
  selector:
    matchLabels:
      app: mongodb      # has to match .spec.template.metadata.labels
  serviceName: mongodb-headless-svc
  replicas: 3         # by default is 1
  #minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: mongodb    # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongodb-app
        image: mongo
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: local-persistent-volume
          mountPath: /data/db    # CHANGE
      volumes:
      - name: local-persistent-volume
        persistentVolumeClaim:
          claimName: my-claim
  
